title: GHTNS
description: Memorializing personal experiences and thoughts 
github_username:  jalangle

# Build settings
markdown: kramdown
theme: minima

collections:
  visit:
    output: true
    markdown: kramdown
    theme: minima

defaults:
  - scope:
      path: ""
      type: "visit"
    values:
      layout: "page"

plugins:
  - jekyll-feed